// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * AuthLoginIn
 */
export type AuthLoginIn = {
    /**
     * Phone
     */
    phone: string;
    /**
     * Password
     */
    password: string;
};

/**
 * AuthMeOut
 */
export type AuthMeOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Phone
     */
    phone: string;
    /**
     * Fio
     */
    fio?: string | null;
    /**
     * Selected Cabinet Id
     */
    selected_cabinet_id: number;
    /**
     * Cabinets
     */
    cabinets: Array<CabinetAccessOut>;
};

/**
 * AuthSelectCabinetIn
 */
export type AuthSelectCabinetIn = {
    /**
     * Cabinet Id
     */
    cabinet_id: number;
};

/**
 * AuthTokenOut
 */
export type AuthTokenOut = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * CabinetAccessOut
 */
export type CabinetAccessOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Mp
     */
    mp: string;
    /**
     * Role
     */
    role: string;
};

/**
 * DemandByWarehouseRead
 */
export type DemandByWarehouseRead = {
    /**
     * Observable Item Id
     */
    observable_item_id: number;
    /**
     * Warehouse Name
     */
    warehouse_name: string;
    /**
     * Warehouse Priority
     */
    warehouse_priority?: number | null;
    /**
     * Short Name
     */
    short_name?: string | null;
    /**
     * Needed
     */
    needed?: number | null;
};

/**
 * ErrorOut
 */
export type ErrorOut = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * FullfillCancelIn
 */
export type FullfillCancelIn = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * FullfillCreateIn
 */
export type FullfillCreateIn = {
    /**
     * Mp
     */
    mp?: string;
};

/**
 * FullfillDeliveryRead
 */
export type FullfillDeliveryRead = {
    /**
     * Warehouses
     */
    warehouses?: {
        [key: string]: boolean;
    };
};

/**
 * FullfillDeliveryUpdateIn
 */
export type FullfillDeliveryUpdateIn = {
    /**
     * Warehouses
     */
    warehouses?: {
        [key: string]: boolean;
    };
};

/**
 * FullfillItemRead
 */
export type FullfillItemRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Observable Item Id
     */
    observable_item_id: number;
    /**
     * Qty
     */
    qty: number;
    /**
     * Stock
     */
    stock?: {
        [key: string]: unknown;
    } | null;
};

/**
 * FullfillItemUpsertIn
 */
export type FullfillItemUpsertIn = {
    /**
     * Observable Item Id
     */
    observable_item_id: number;
    /**
     * Qty
     */
    qty: number;
    /**
     * Stock
     */
    stock?: {
        [key: string]: unknown;
    } | null;
};

/**
 * FullfillListItemRead
 */
export type FullfillListItemRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Mp
     */
    mp: string;
    /**
     * Status
     */
    status: string;
    /**
     * Liters
     */
    liters: string;
    /**
     * Boxes
     */
    boxes: string;
    /**
     * Pallets
     */
    pallets: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * FullfillNewRowRead
 */
export type FullfillNewRowRead = {
    /**
     * Observable Item Id
     */
    observable_item_id: number;
    /**
     * Warehouse Name
     */
    warehouse_name: string;
    /**
     * Observable Id
     */
    observable_id?: number | null;
    /**
     * Observable Name
     */
    observable_name?: string | null;
    /**
     * Product Sku
     */
    product_sku?: number | null;
    /**
     * Offer Id
     */
    offer_id?: string | null;
    /**
     * Packing
     */
    packing?: number | null;
    /**
     * Packing Type
     */
    packing_type?: string | null;
    /**
     * Volume
     */
    volume?: string | null;
    /**
     * Barcode
     */
    barcode?: string | null;
    /**
     * In Our Stock
     */
    in_our_stock?: number | null;
    /**
     * Needed
     */
    needed?: number | null;
};

/**
 * FullfillRead
 */
export type FullfillRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Mp
     */
    mp: string;
    /**
     * Status
     */
    status: string;
    /**
     * Liters
     */
    liters: string;
    /**
     * Boxes
     */
    boxes: string;
    /**
     * Pallets
     */
    pallets: string;
    /**
     * In Delivery Warehouses
     */
    in_delivery_warehouses?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Items
     */
    items: Array<FullfillItemRead>;
};

/**
 * FullfillUpdateIn
 */
export type FullfillUpdateIn = {
    /**
     * Items
     */
    items: Array<FullfillItemUpsertIn>;
    /**
     * Liters
     */
    liters?: number | string | null;
    /**
     * Boxes
     */
    boxes?: number | string | null;
    /**
     * Pallets
     */
    pallets?: number | string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ObservableInWayRead
 */
export type ObservableInWayRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Supplier Id
     */
    supplier_id: number;
    /**
     * Supplier Name
     */
    supplier_name: string;
    /**
     * Name
     */
    name: string;
    /**
     * Price
     */
    price?: string | null;
    /**
     * In Way
     */
    in_way: number;
};

/**
 * ObservableInWayUpdate
 */
export type ObservableInWayUpdate = {
    /**
     * Id
     */
    id: number;
    /**
     * In Way
     */
    in_way: number;
};

/**
 * ObservableStockAdd
 */
export type ObservableStockAdd = {
    /**
     * Id
     */
    id: number;
    /**
     * Add
     *
     * Количество, которое нужно прибавить к in_our_stock
     */
    add: number;
};

/**
 * ObservableStockRead
 */
export type ObservableStockRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Supplier Id
     */
    supplier_id: number;
    /**
     * Supplier Name
     */
    supplier_name: string;
    /**
     * Name
     */
    name: string;
    /**
     * Price
     */
    price?: string | null;
    /**
     * In Our Stock
     */
    in_our_stock: number;
};

/**
 * OrderCancelIn
 */
export type OrderCancelIn = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * OrderCreateIn
 */
export type OrderCreateIn = {
    /**
     * Observable Ids
     */
    observable_ids: Array<number>;
};

/**
 * OrderItemAdditionalUpdate
 */
export type OrderItemAdditionalUpdate = {
    /**
     * Id
     *
     * ID позиции заказа (order_items.id)
     */
    id: number;
    /**
     * Additional
     *
     * Дополнительное количество
     */
    additional: number;
};

/**
 * OrderItemRead
 */
export type OrderItemRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Observable Id
     */
    observable_id: number;
    /**
     * Supplier Id
     */
    supplier_id: number;
    /**
     * Supplier Name
     */
    supplier_name?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Min Count
     */
    min_count?: number | null;
    /**
     * Needed
     */
    needed?: number | null;
    /**
     * Additional
     */
    additional: number;
    /**
     * Price
     */
    price?: string | null;
};

/**
 * OrderListItemRead
 */
export type OrderListItemRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * OrderRead
 */
export type OrderRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Items
     */
    items: Array<OrderItemRead>;
};

/**
 * OrderUpdateIn
 */
export type OrderUpdateIn = {
    /**
     * Items
     */
    items: Array<OrderItemAdditionalUpdate>;
};

/**
 * Paginated[FullfillListItemRead]
 */
export type PaginatedFullfillListItemRead = {
    /**
     * Items
     */
    items: Array<FullfillListItemRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
};

/**
 * Paginated[OrderListItemRead]
 */
export type PaginatedOrderListItemRead = {
    /**
     * Items
     */
    items: Array<OrderListItemRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
};

/**
 * Paginated[SupplierRead]
 */
export type PaginatedSupplierRead = {
    /**
     * Items
     */
    items: Array<SupplierRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
};

/**
 * Paginated[SupplyDemandRead]
 */
export type PaginatedSupplyDemandRead = {
    /**
     * Items
     */
    items: Array<SupplyDemandRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
};

/**
 * RecalcLaunchOut
 */
export type RecalcLaunchOut = {
    /**
     * Run Id
     */
    run_id: string;
};

/**
 * RecalcStatusOut
 */
export type RecalcStatusOut = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * StockByProductWarehouseRead
 */
export type StockByProductWarehouseRead = {
    /**
     * Product Sku
     */
    product_sku: number;
    /**
     * Warehouse Name
     */
    warehouse_name: string;
    /**
     * Short Name
     */
    short_name?: string | null;
    /**
     * Priority
     */
    priority?: number | null;
    /**
     * Visible
     */
    visible?: boolean | null;
    /**
     * Transit Stock Count
     */
    transit_stock_count?: number | null;
    /**
     * Available Stock Count
     */
    available_stock_count?: number | null;
    /**
     * Requested Stock Count
     */
    requested_stock_count?: number | null;
    /**
     * Avg Sale
     */
    avg_sale?: string | null;
    /**
     * Needed
     */
    needed?: number | null;
};

/**
 * StockVisibilitySetIn
 */
export type StockVisibilitySetIn = {
    /**
     * Product Sku
     */
    product_sku: number;
    /**
     * Warehouse Name
     */
    warehouse_name: string;
    /**
     * Visible
     */
    visible: boolean;
};

/**
 * StockVisibilitySetOut
 */
export type StockVisibilitySetOut = {
    /**
     * Product Sku
     */
    product_sku: number;
    /**
     * Warehouse Name
     */
    warehouse_name: string;
    /**
     * Visible
     */
    visible: boolean;
};

/**
 * SupplierCreate
 */
export type SupplierCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * SupplierRead
 */
export type SupplierRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * SupplierUpdate
 */
export type SupplierUpdate = {
    /**
     * Name
     */
    name: string;
};

/**
 * SupplyDemandRead
 */
export type SupplyDemandRead = {
    /**
     * Item Id
     */
    item_id: number;
    /**
     * Observable Id
     */
    observable_id: number;
    /**
     * Observable Name
     */
    observable_name: string;
    /**
     * Supplier Id
     */
    supplier_id: number;
    /**
     * Supplier Name
     */
    supplier_name: string;
    /**
     * Price
     */
    price?: string | null;
    /**
     * Min Count
     */
    min_count?: number | null;
    /**
     * In Our Stock
     */
    in_our_stock?: number | null;
    /**
     * In Way
     */
    in_way?: number | null;
    /**
     * Product Sku
     */
    product_sku: number;
    /**
     * Offer Id
     */
    offer_id?: string | null;
    /**
     * Product Name
     */
    product_name?: string | null;
    /**
     * Packing
     */
    packing: number;
    /**
     * Mp
     */
    mp?: string | null;
    /**
     * Item Needed
     */
    item_needed?: number | null;
    /**
     * Need
     */
    need?: number | null;
    /**
     * Needmin
     */
    needmin?: number | null;
    /**
     * Stock Reserve
     */
    stock_reserve?: number | null;
    /**
     * Total Need
     */
    total_need?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WarehouseSettingRead
 */
export type WarehouseSettingRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Warehouse Name
     */
    warehouse_name: string;
    /**
     * Short Name
     */
    short_name?: string | null;
    /**
     * Priority
     */
    priority: number;
    /**
     * Visible
     */
    visible: boolean;
    /**
     * Period Stock
     */
    period_stock: number;
    /**
     * Period Delivery
     */
    period_delivery: number;
    /**
     * Mp
     */
    mp: string;
};

/**
 * WarehouseSettingUpdate
 */
export type WarehouseSettingUpdate = {
    /**
     * Id
     */
    id: number;
    /**
     * Short Name
     */
    short_name?: string | null;
    /**
     * Priority
     */
    priority?: number | null;
    /**
     * Visible
     */
    visible?: boolean | null;
    /**
     * Period Stock
     */
    period_stock?: number | null;
    /**
     * Period Delivery
     */
    period_delivery?: number | null;
};

/**
 * WarehousesUpdateIn
 */
export type WarehousesUpdateIn = {
    /**
     * Items
     */
    items: Array<WarehouseSettingUpdate>;
};

export type LoginAuthLoginPostData = {
    body: AuthLoginIn;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: AuthTokenOut;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type MeAuthMeGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type MeAuthMeGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type MeAuthMeGetError = MeAuthMeGetErrors[keyof MeAuthMeGetErrors];

export type MeAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: AuthMeOut;
};

export type MeAuthMeGetResponse = MeAuthMeGetResponses[keyof MeAuthMeGetResponses];

export type SelectCabinetAuthSelectCabinetPostData = {
    body: AuthSelectCabinetIn;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/auth/select-cabinet';
};

export type SelectCabinetAuthSelectCabinetPostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type SelectCabinetAuthSelectCabinetPostError = SelectCabinetAuthSelectCabinetPostErrors[keyof SelectCabinetAuthSelectCabinetPostErrors];

export type SelectCabinetAuthSelectCabinetPostResponses = {
    /**
     * Successful Response
     */
    200: AuthTokenOut;
};

export type SelectCabinetAuthSelectCabinetPostResponse = SelectCabinetAuthSelectCabinetPostResponses[keyof SelectCabinetAuthSelectCabinetPostResponses];

export type ListSuppliersSuppliersGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Order By
         */
        order_by?: string | null;
        /**
         * Q
         */
        q?: string | null;
    };
    url: '/suppliers';
};

export type ListSuppliersSuppliersGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type ListSuppliersSuppliersGetError = ListSuppliersSuppliersGetErrors[keyof ListSuppliersSuppliersGetErrors];

export type ListSuppliersSuppliersGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedSupplierRead;
};

export type ListSuppliersSuppliersGetResponse = ListSuppliersSuppliersGetResponses[keyof ListSuppliersSuppliersGetResponses];

export type CreateSupplierSuppliersPostData = {
    body: SupplierCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/suppliers';
};

export type CreateSupplierSuppliersPostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type CreateSupplierSuppliersPostError = CreateSupplierSuppliersPostErrors[keyof CreateSupplierSuppliersPostErrors];

export type CreateSupplierSuppliersPostResponses = {
    /**
     * Successful Response
     */
    201: SupplierRead;
};

export type CreateSupplierSuppliersPostResponse = CreateSupplierSuppliersPostResponses[keyof CreateSupplierSuppliersPostResponses];

export type DeleteSupplierSuppliersSupplierIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Supplier Id
         */
        supplier_id: number;
    };
    query?: never;
    url: '/suppliers/{supplier_id}';
};

export type DeleteSupplierSuppliersSupplierIdDeleteErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type DeleteSupplierSuppliersSupplierIdDeleteError = DeleteSupplierSuppliersSupplierIdDeleteErrors[keyof DeleteSupplierSuppliersSupplierIdDeleteErrors];

export type DeleteSupplierSuppliersSupplierIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSupplierSuppliersSupplierIdDeleteResponse = DeleteSupplierSuppliersSupplierIdDeleteResponses[keyof DeleteSupplierSuppliersSupplierIdDeleteResponses];

export type UpdateSupplierSuppliersSupplierIdPatchData = {
    body: SupplierUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Supplier Id
         */
        supplier_id: number;
    };
    query?: never;
    url: '/suppliers/{supplier_id}';
};

export type UpdateSupplierSuppliersSupplierIdPatchErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type UpdateSupplierSuppliersSupplierIdPatchError = UpdateSupplierSuppliersSupplierIdPatchErrors[keyof UpdateSupplierSuppliersSupplierIdPatchErrors];

export type UpdateSupplierSuppliersSupplierIdPatchResponses = {
    /**
     * Successful Response
     */
    200: SupplierRead;
};

export type UpdateSupplierSuppliersSupplierIdPatchResponse = UpdateSupplierSuppliersSupplierIdPatchResponses[keyof UpdateSupplierSuppliersSupplierIdPatchResponses];

export type SupplyDemandListData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Order By
         */
        order_by?: string | null;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Supplier Id
         */
        supplier_id?: number | null;
    };
    url: '/supply/demand';
};

export type SupplyDemandListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SupplyDemandListError = SupplyDemandListErrors[keyof SupplyDemandListErrors];

export type SupplyDemandListResponses = {
    /**
     * Successful Response
     */
    200: PaginatedSupplyDemandRead;
};

export type SupplyDemandListResponse = SupplyDemandListResponses[keyof SupplyDemandListResponses];

export type ListDemandByWarehousesSupplyDemandWarehousesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/supply/demand/warehouses';
};

export type ListDemandByWarehousesSupplyDemandWarehousesGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type ListDemandByWarehousesSupplyDemandWarehousesGetError = ListDemandByWarehousesSupplyDemandWarehousesGetErrors[keyof ListDemandByWarehousesSupplyDemandWarehousesGetErrors];

export type ListDemandByWarehousesSupplyDemandWarehousesGetResponses = {
    /**
     * Response List Demand By Warehouses Supply Demand Warehouses Get
     *
     * Successful Response
     */
    200: Array<DemandByWarehouseRead>;
};

export type ListDemandByWarehousesSupplyDemandWarehousesGetResponse = ListDemandByWarehousesSupplyDemandWarehousesGetResponses[keyof ListDemandByWarehousesSupplyDemandWarehousesGetResponses];

export type RecalcSupplySupplyRecalculatePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/supply/recalculate';
};

export type RecalcSupplySupplyRecalculatePostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type RecalcSupplySupplyRecalculatePostError = RecalcSupplySupplyRecalculatePostErrors[keyof RecalcSupplySupplyRecalculatePostErrors];

export type RecalcSupplySupplyRecalculatePostResponses = {
    /**
     * Successful Response
     */
    202: RecalcLaunchOut;
};

export type RecalcSupplySupplyRecalculatePostResponse = RecalcSupplySupplyRecalculatePostResponses[keyof RecalcSupplySupplyRecalculatePostResponses];

export type RecalcSupplyStatusSupplyRecalculateStatusRunIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/supply/recalculate/status/{run_id}';
};

export type RecalcSupplyStatusSupplyRecalculateStatusRunIdGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type RecalcSupplyStatusSupplyRecalculateStatusRunIdGetError = RecalcSupplyStatusSupplyRecalculateStatusRunIdGetErrors[keyof RecalcSupplyStatusSupplyRecalculateStatusRunIdGetErrors];

export type RecalcSupplyStatusSupplyRecalculateStatusRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: RecalcStatusOut;
};

export type RecalcSupplyStatusSupplyRecalculateStatusRunIdGetResponse = RecalcSupplyStatusSupplyRecalculateStatusRunIdGetResponses[keyof RecalcSupplyStatusSupplyRecalculateStatusRunIdGetResponses];

export type ProductStockStockProductProductSkuGetData = {
    body?: never;
    path: {
        /**
         * Product Sku
         */
        product_sku: number;
    };
    query?: never;
    url: '/stock/product/{product_sku}';
};

export type ProductStockStockProductProductSkuGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductStockStockProductProductSkuGetError = ProductStockStockProductProductSkuGetErrors[keyof ProductStockStockProductProductSkuGetErrors];

export type ProductStockStockProductProductSkuGetResponses = {
    /**
     * Response Product Stock Stock Product  Product Sku  Get
     *
     * Successful Response
     */
    200: Array<StockByProductWarehouseRead>;
};

export type ProductStockStockProductProductSkuGetResponse = ProductStockStockProductProductSkuGetResponses[keyof ProductStockStockProductProductSkuGetResponses];

export type SetVisibleStockVisiblePostData = {
    body: StockVisibilitySetIn;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/stock/visible';
};

export type SetVisibleStockVisiblePostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type SetVisibleStockVisiblePostError = SetVisibleStockVisiblePostErrors[keyof SetVisibleStockVisiblePostErrors];

export type SetVisibleStockVisiblePostResponses = {
    /**
     * Successful Response
     */
    200: StockVisibilitySetOut;
};

export type SetVisibleStockVisiblePostResponse = SetVisibleStockVisiblePostResponses[keyof SetVisibleStockVisiblePostResponses];

export type ListOrdersOrdersGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Order By
         */
        order_by?: string | null;
    };
    url: '/orders';
};

export type ListOrdersOrdersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrdersOrdersGetError = ListOrdersOrdersGetErrors[keyof ListOrdersOrdersGetErrors];

export type ListOrdersOrdersGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedOrderListItemRead;
};

export type ListOrdersOrdersGetResponse = ListOrdersOrdersGetResponses[keyof ListOrdersOrdersGetResponses];

export type CreateOrderOrdersPostData = {
    body: OrderCreateIn;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/orders';
};

export type CreateOrderOrdersPostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type CreateOrderOrdersPostError = CreateOrderOrdersPostErrors[keyof CreateOrderOrdersPostErrors];

export type CreateOrderOrdersPostResponses = {
    /**
     * Successful Response
     */
    201: OrderRead;
};

export type CreateOrderOrdersPostResponse = CreateOrderOrdersPostResponses[keyof CreateOrderOrdersPostResponses];

export type DeleteOrderOrdersOrderIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Order Id
         */
        order_id: number;
    };
    query?: never;
    url: '/orders/{order_id}';
};

export type DeleteOrderOrdersOrderIdDeleteErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type DeleteOrderOrdersOrderIdDeleteError = DeleteOrderOrdersOrderIdDeleteErrors[keyof DeleteOrderOrdersOrderIdDeleteErrors];

export type DeleteOrderOrdersOrderIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteOrderOrdersOrderIdDeleteResponse = DeleteOrderOrdersOrderIdDeleteResponses[keyof DeleteOrderOrdersOrderIdDeleteResponses];

export type GetOrderOrdersOrderIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Order Id
         */
        order_id: number;
    };
    query?: never;
    url: '/orders/{order_id}';
};

export type GetOrderOrdersOrderIdGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type GetOrderOrdersOrderIdGetError = GetOrderOrdersOrderIdGetErrors[keyof GetOrderOrdersOrderIdGetErrors];

export type GetOrderOrdersOrderIdGetResponses = {
    /**
     * Successful Response
     */
    200: OrderRead;
};

export type GetOrderOrdersOrderIdGetResponse = GetOrderOrdersOrderIdGetResponses[keyof GetOrderOrdersOrderIdGetResponses];

export type UpdateOrderOrdersOrderIdPatchData = {
    body: OrderUpdateIn;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Order Id
         */
        order_id: number;
    };
    query?: never;
    url: '/orders/{order_id}';
};

export type UpdateOrderOrdersOrderIdPatchErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type UpdateOrderOrdersOrderIdPatchError = UpdateOrderOrdersOrderIdPatchErrors[keyof UpdateOrderOrdersOrderIdPatchErrors];

export type UpdateOrderOrdersOrderIdPatchResponses = {
    /**
     * Successful Response
     */
    200: OrderRead;
};

export type UpdateOrderOrdersOrderIdPatchResponse = UpdateOrderOrdersOrderIdPatchResponses[keyof UpdateOrderOrdersOrderIdPatchResponses];

export type ApproveOrderOrdersOrderIdApprovePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Order Id
         */
        order_id: number;
    };
    query?: never;
    url: '/orders/{order_id}/approve';
};

export type ApproveOrderOrdersOrderIdApprovePostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type ApproveOrderOrdersOrderIdApprovePostError = ApproveOrderOrdersOrderIdApprovePostErrors[keyof ApproveOrderOrdersOrderIdApprovePostErrors];

export type ApproveOrderOrdersOrderIdApprovePostResponses = {
    /**
     * Successful Response
     */
    200: OrderRead;
};

export type ApproveOrderOrdersOrderIdApprovePostResponse = ApproveOrderOrdersOrderIdApprovePostResponses[keyof ApproveOrderOrdersOrderIdApprovePostResponses];

export type CancelOrderOrdersOrderIdCancelPostData = {
    body: OrderCancelIn;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Order Id
         */
        order_id: number;
    };
    query?: never;
    url: '/orders/{order_id}/cancel';
};

export type CancelOrderOrdersOrderIdCancelPostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type CancelOrderOrdersOrderIdCancelPostError = CancelOrderOrdersOrderIdCancelPostErrors[keyof CancelOrderOrdersOrderIdCancelPostErrors];

export type CancelOrderOrdersOrderIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: OrderRead;
};

export type CancelOrderOrdersOrderIdCancelPostResponse = CancelOrderOrdersOrderIdCancelPostResponses[keyof CancelOrderOrdersOrderIdCancelPostResponses];

export type ListInwayObservablesInwayGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/observables/inway';
};

export type ListInwayObservablesInwayGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type ListInwayObservablesInwayGetError = ListInwayObservablesInwayGetErrors[keyof ListInwayObservablesInwayGetErrors];

export type ListInwayObservablesInwayGetResponses = {
    /**
     * Response List Inway Observables Inway Get
     *
     * Successful Response
     */
    200: Array<ObservableInWayRead>;
};

export type ListInwayObservablesInwayGetResponse = ListInwayObservablesInwayGetResponses[keyof ListInwayObservablesInwayGetResponses];

export type UpdateInwayObservablesInwayPatchData = {
    /**
     * Payload
     */
    body: Array<ObservableInWayUpdate>;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/observables/inway';
};

export type UpdateInwayObservablesInwayPatchErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type UpdateInwayObservablesInwayPatchError = UpdateInwayObservablesInwayPatchErrors[keyof UpdateInwayObservablesInwayPatchErrors];

export type UpdateInwayObservablesInwayPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateInwayObservablesInwayPatchResponse = UpdateInwayObservablesInwayPatchResponses[keyof UpdateInwayObservablesInwayPatchResponses];

export type ListStockObservablesStockGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/observables/stock';
};

export type ListStockObservablesStockGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type ListStockObservablesStockGetError = ListStockObservablesStockGetErrors[keyof ListStockObservablesStockGetErrors];

export type ListStockObservablesStockGetResponses = {
    /**
     * Response List Stock Observables Stock Get
     *
     * Successful Response
     */
    200: Array<ObservableStockRead>;
};

export type ListStockObservablesStockGetResponse = ListStockObservablesStockGetResponses[keyof ListStockObservablesStockGetResponses];

export type AddStockObservablesStockPatchData = {
    /**
     * Payload
     */
    body: Array<ObservableStockAdd>;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/observables/stock';
};

export type AddStockObservablesStockPatchErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type AddStockObservablesStockPatchError = AddStockObservablesStockPatchErrors[keyof AddStockObservablesStockPatchErrors];

export type AddStockObservablesStockPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AddStockObservablesStockPatchResponse = AddStockObservablesStockPatchResponses[keyof AddStockObservablesStockPatchResponses];

export type ListFullfillFullfillGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Order By
         */
        order_by?: string | null;
    };
    url: '/fullfill';
};

export type ListFullfillFullfillGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFullfillFullfillGetError = ListFullfillFullfillGetErrors[keyof ListFullfillFullfillGetErrors];

export type ListFullfillFullfillGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedFullfillListItemRead;
};

export type ListFullfillFullfillGetResponse = ListFullfillFullfillGetResponses[keyof ListFullfillFullfillGetResponses];

export type CreateFullfillFullfillPostData = {
    body: FullfillCreateIn;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/fullfill';
};

export type CreateFullfillFullfillPostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type CreateFullfillFullfillPostError = CreateFullfillFullfillPostErrors[keyof CreateFullfillFullfillPostErrors];

export type CreateFullfillFullfillPostResponses = {
    /**
     * Successful Response
     */
    201: FullfillRead;
};

export type CreateFullfillFullfillPostResponse = CreateFullfillFullfillPostResponses[keyof CreateFullfillFullfillPostResponses];

export type NewFullfillDataFullfillNewMpGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Mp
         */
        mp: string;
    };
    query?: never;
    url: '/fullfill/new/{mp}';
};

export type NewFullfillDataFullfillNewMpGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type NewFullfillDataFullfillNewMpGetError = NewFullfillDataFullfillNewMpGetErrors[keyof NewFullfillDataFullfillNewMpGetErrors];

export type NewFullfillDataFullfillNewMpGetResponses = {
    /**
     * Response New Fullfill Data Fullfill New  Mp  Get
     *
     * Successful Response
     */
    200: Array<FullfillNewRowRead>;
};

export type NewFullfillDataFullfillNewMpGetResponse = NewFullfillDataFullfillNewMpGetResponses[keyof NewFullfillDataFullfillNewMpGetResponses];

export type DeleteFullfillFullfillFullfillIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Fullfill Id
         */
        fullfill_id: number;
    };
    query?: never;
    url: '/fullfill/{fullfill_id}';
};

export type DeleteFullfillFullfillFullfillIdDeleteErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type DeleteFullfillFullfillFullfillIdDeleteError = DeleteFullfillFullfillFullfillIdDeleteErrors[keyof DeleteFullfillFullfillFullfillIdDeleteErrors];

export type DeleteFullfillFullfillFullfillIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteFullfillFullfillFullfillIdDeleteResponse = DeleteFullfillFullfillFullfillIdDeleteResponses[keyof DeleteFullfillFullfillFullfillIdDeleteResponses];

export type GetFullfillFullfillFullfillIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Fullfill Id
         */
        fullfill_id: number;
    };
    query?: never;
    url: '/fullfill/{fullfill_id}';
};

export type GetFullfillFullfillFullfillIdGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type GetFullfillFullfillFullfillIdGetError = GetFullfillFullfillFullfillIdGetErrors[keyof GetFullfillFullfillFullfillIdGetErrors];

export type GetFullfillFullfillFullfillIdGetResponses = {
    /**
     * Successful Response
     */
    200: FullfillRead;
};

export type GetFullfillFullfillFullfillIdGetResponse = GetFullfillFullfillFullfillIdGetResponses[keyof GetFullfillFullfillFullfillIdGetResponses];

export type UpdateFullfillFullfillFullfillIdPatchData = {
    body: FullfillUpdateIn;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Fullfill Id
         */
        fullfill_id: number;
    };
    query?: never;
    url: '/fullfill/{fullfill_id}';
};

export type UpdateFullfillFullfillFullfillIdPatchErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type UpdateFullfillFullfillFullfillIdPatchError = UpdateFullfillFullfillFullfillIdPatchErrors[keyof UpdateFullfillFullfillFullfillIdPatchErrors];

export type UpdateFullfillFullfillFullfillIdPatchResponses = {
    /**
     * Successful Response
     */
    200: FullfillRead;
};

export type UpdateFullfillFullfillFullfillIdPatchResponse = UpdateFullfillFullfillFullfillIdPatchResponses[keyof UpdateFullfillFullfillFullfillIdPatchResponses];

export type ApplyFullfillFullfillFullfillIdApplyPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Fullfill Id
         */
        fullfill_id: number;
    };
    query?: never;
    url: '/fullfill/{fullfill_id}/apply';
};

export type ApplyFullfillFullfillFullfillIdApplyPostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type ApplyFullfillFullfillFullfillIdApplyPostError = ApplyFullfillFullfillFullfillIdApplyPostErrors[keyof ApplyFullfillFullfillFullfillIdApplyPostErrors];

export type ApplyFullfillFullfillFullfillIdApplyPostResponses = {
    /**
     * Successful Response
     */
    200: FullfillRead;
};

export type ApplyFullfillFullfillFullfillIdApplyPostResponse = ApplyFullfillFullfillFullfillIdApplyPostResponses[keyof ApplyFullfillFullfillFullfillIdApplyPostResponses];

export type CancelFullfillFullfillFullfillIdCancelPostData = {
    body: FullfillCancelIn;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Fullfill Id
         */
        fullfill_id: number;
    };
    query?: never;
    url: '/fullfill/{fullfill_id}/cancel';
};

export type CancelFullfillFullfillFullfillIdCancelPostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type CancelFullfillFullfillFullfillIdCancelPostError = CancelFullfillFullfillFullfillIdCancelPostErrors[keyof CancelFullfillFullfillFullfillIdCancelPostErrors];

export type CancelFullfillFullfillFullfillIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: FullfillRead;
};

export type CancelFullfillFullfillFullfillIdCancelPostResponse = CancelFullfillFullfillFullfillIdCancelPostResponses[keyof CancelFullfillFullfillFullfillIdCancelPostResponses];

export type GetDeliveryFullfillFullfillIdDeliveryGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Fullfill Id
         */
        fullfill_id: number;
    };
    query?: never;
    url: '/fullfill/{fullfill_id}/delivery';
};

export type GetDeliveryFullfillFullfillIdDeliveryGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type GetDeliveryFullfillFullfillIdDeliveryGetError = GetDeliveryFullfillFullfillIdDeliveryGetErrors[keyof GetDeliveryFullfillFullfillIdDeliveryGetErrors];

export type GetDeliveryFullfillFullfillIdDeliveryGetResponses = {
    /**
     * Successful Response
     */
    200: FullfillDeliveryRead;
};

export type GetDeliveryFullfillFullfillIdDeliveryGetResponse = GetDeliveryFullfillFullfillIdDeliveryGetResponses[keyof GetDeliveryFullfillFullfillIdDeliveryGetResponses];

export type SetDeliveryFullfillFullfillIdDeliveryPostData = {
    body: FullfillDeliveryUpdateIn;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Fullfill Id
         */
        fullfill_id: number;
    };
    query?: never;
    url: '/fullfill/{fullfill_id}/delivery';
};

export type SetDeliveryFullfillFullfillIdDeliveryPostErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type SetDeliveryFullfillFullfillIdDeliveryPostError = SetDeliveryFullfillFullfillIdDeliveryPostErrors[keyof SetDeliveryFullfillFullfillIdDeliveryPostErrors];

export type SetDeliveryFullfillFullfillIdDeliveryPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type SetDeliveryFullfillFullfillIdDeliveryPostResponse = SetDeliveryFullfillFullfillIdDeliveryPostResponses[keyof SetDeliveryFullfillFullfillIdDeliveryPostResponses];

export type ListWarehousesWarehousesMpGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Mp
         */
        mp: string;
    };
    query?: never;
    url: '/warehouses/{mp}';
};

export type ListWarehousesWarehousesMpGetErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type ListWarehousesWarehousesMpGetError = ListWarehousesWarehousesMpGetErrors[keyof ListWarehousesWarehousesMpGetErrors];

export type ListWarehousesWarehousesMpGetResponses = {
    /**
     * Response List Warehouses Warehouses  Mp  Get
     *
     * Successful Response
     */
    200: Array<WarehouseSettingRead>;
};

export type ListWarehousesWarehousesMpGetResponse = ListWarehousesWarehousesMpGetResponses[keyof ListWarehousesWarehousesMpGetResponses];

export type UpdateWarehousesWarehousesMpPatchData = {
    body: WarehousesUpdateIn;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Mp
         */
        mp: string;
    };
    query?: never;
    url: '/warehouses/{mp}';
};

export type UpdateWarehousesWarehousesMpPatchErrors = {
    /**
     * Bad request
     */
    400: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict
     */
    409: ErrorOut;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorOut;
    /**
     * External service error
     */
    502: ErrorOut;
};

export type UpdateWarehousesWarehousesMpPatchError = UpdateWarehousesWarehousesMpPatchErrors[keyof UpdateWarehousesWarehousesMpPatchErrors];

export type UpdateWarehousesWarehousesMpPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateWarehousesWarehousesMpPatchResponse = UpdateWarehousesWarehousesMpPatchResponses[keyof UpdateWarehousesWarehousesMpPatchResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
